# Generated by Django 3.1.2 on 2020-10-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userrequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='post',
            field=models.JSONField(default=dict),
        ),
    ]
